### ISSUE TITLE
Need Opencv Auton 

### ISSUE THREAD

**Issue by adam-the-student** [adam-the-student/MoiCenterStage#1]
For PPP (purple pixel placement)

**Comment by adam-the-student** [comment]
I think the pipelines are functioning, however we just need to add the Pusher code

**Comment by Caffeiphile** [comment]
> I think the pipelines are functioning, however we just need to add the Pusher code

Can you please elaborate on what you mean by pusher.

**Comment by Caffeiphile** [comment]
We done, make a new repo plz
