### ISSUE TITLE
Roadrunner BoilerPlate

### ISSUE THREAD

**Issue by adam-the-student** [adam-the-student/MoiCenterStage#2]
Need to add the boilerplate for roadrunner. Gradle imp's drive util tracking opmodes, ect.

**Comment by adam-the-student** [comment]
Added all base dependencies and Opmode's as of commit f8787458045934ae2f65d0d5feb33ad6b636f46b 
Waiting for a successful robot build to confirm pull to Vengeance branch.

**Comment by Caffeiphile** [comment]
N/a
